[2025-07-04T03:00:01.757+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [queued]>
[2025-07-04T03:00:01.768+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [queued]>
[2025-07-04T03:00:01.769+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-07-04T03:00:01.787+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): fetch_and_insert> on 2025-07-04 02:00:00+00:00
[2025-07-04T03:00:01.798+0000] {standard_task_runner.py:57} INFO - Started process 231 to run task
[2025-07-04T03:00:01.803+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingest_dag', 'fetch_and_insert', 'scheduled__2025-07-04T02:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingest_dag.py', '--cfg-path', '/tmp/tmpk5ehzgle']
[2025-07-04T03:00:01.807+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask fetch_and_insert
[2025-07-04T03:00:01.898+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [running]> on host b87c05c3cf38
[2025-07-04T03:00:02.006+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='weather_ingest_dag' AIRFLOW_CTX_TASK_ID='fetch_and_insert' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-04T02:00:00+00:00'
[2025-07-04T03:00:02.008+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-04T03:00:02.011+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/fetch_weather.py']
[2025-07-04T03:00:02.030+0000] {subprocess.py:86} INFO - Output:
[2025-07-04T03:00:03.562+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-04T03:00:03.563+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/fetch_weather.py", line 73, in <module>
[2025-07-04T03:00:03.564+0000] {subprocess.py:93} INFO -     raw_data = fetch_weather_data()
[2025-07-04T03:00:03.566+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/fetch_weather.py", line 20, in fetch_weather_data
[2025-07-04T03:00:03.567+0000] {subprocess.py:93} INFO -     response.raise_for_status()
[2025-07-04T03:00:03.567+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
[2025-07-04T03:00:03.568+0000] {subprocess.py:93} INFO -     raise HTTPError(http_error_msg, response=self)
[2025-07-04T03:00:03.569+0000] {subprocess.py:93} INFO - requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://pro.openweathermap.org/data/2.5/forecast/hourly?lat=42.3865&lon=-71.0228&cnt=10&appid=7d6a64fd9c0466f533754585e33e4406&mode=json
[2025-07-04T03:00:03.603+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-04T03:00:03.620+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-04T03:00:03.625+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_ingest_dag, task_id=fetch_and_insert, execution_date=20250704T020000, start_date=20250704T030001, end_date=20250704T030003
[2025-07-04T03:00:03.646+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task fetch_and_insert (Bash command failed. The command returned a non-zero exit code 1.; 231)
[2025-07-04T03:00:03.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T03:00:03.693+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T03:31:31.613+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [queued]>
[2025-07-04T03:31:31.631+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [queued]>
[2025-07-04T03:31:31.632+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-07-04T03:31:31.660+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): fetch_and_insert> on 2025-07-04 02:00:00+00:00
[2025-07-04T03:31:31.683+0000] {standard_task_runner.py:57} INFO - Started process 208 to run task
[2025-07-04T03:31:31.688+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingest_dag', 'fetch_and_insert', 'scheduled__2025-07-04T02:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingest_dag.py', '--cfg-path', '/tmp/tmp8cv9f64_']
[2025-07-04T03:31:31.707+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask fetch_and_insert
[2025-07-04T03:31:31.836+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_ingest_dag.fetch_and_insert scheduled__2025-07-04T02:00:00+00:00 [running]> on host 74a12dde0a9a
[2025-07-04T03:31:31.979+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='weather_ingest_dag' AIRFLOW_CTX_TASK_ID='fetch_and_insert' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-04T02:00:00+00:00'
[2025-07-04T03:31:31.984+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-04T03:31:31.985+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/fetch_weather.py']
[2025-07-04T03:31:32.003+0000] {subprocess.py:86} INFO - Output:
[2025-07-04T03:31:33.799+0000] {subprocess.py:93} INFO - API Key is: 7d6a64fd9c0466f533754585e33e4406
[2025-07-04T03:31:33.800+0000] {subprocess.py:93} INFO - Weather data fetched and inserted into Postgres successfully.
[2025-07-04T03:31:33.834+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-07-04T03:31:33.886+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_ingest_dag, task_id=fetch_and_insert, execution_date=20250704T020000, start_date=20250704T033131, end_date=20250704T033133
[2025-07-04T03:31:33.955+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-04T03:31:34.011+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
